const actionTypes = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',

    //USER
    GET_USER: 'GET_USER',

    //BAIXE
    GET_BAIXE: 'GET_BAIXE',
    GET_BAIXE_FAILED: 'GET_BAIXE_FAILED',
};

export default actionTypes;
